name: Check and clean files

on: pull_request

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install exiftool
        run: sudo apt install exiftool

      - name: Run script
        run: node ./.github/check.js

      - name: Commit changed files
        if: steps.changed.outputs.files_changed == 'true'
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update files"
