name: Check files

on:
  pull_request:
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.head_ref }}

      - name: Install packages
        run: npm install exiftool-vendored@26

      - if: runner.debug == '1'
        uses: mxschmitt/action-tmate@v3

      - name: Run script
        run: node ./.github/check.mjs
