name: Clean files

on:
  push:
    branches:
      - main

jobs:
  clean:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install packages
        run: npm install exiftool-vendored@26

      - if: runner.debug == '1'
        uses: mxschmitt/action-tmate@v3

      - name: Run script
        run: bun ./.github/clean.mjs

      - name: Commit changed files
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Clean files"
