name: Clean files

on:
  push:
    branches:
      - main

jobs:
  clean:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install packages
        run: |
          bun add exiftool-vendored@26
          bun install

      - if: runner.debug == '1'
        uses: mxschmitt/action-tmate@v3

      - name: Run script
        run: bun ./.github/clean.js

      - name: Commit changed files
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Clean files"
